import React, { useEffect, useMemo, useState } from 'react';
import { FiDownload, FiFileText, FiPrinter, FiRefreshCw } from 'react-icons/fi';
import { toast } from 'react-toastify';
import api from '../../api/axios';

type ReportType = 'course' | 'enrollment' | 'hostel' | 'exam-fee';
const labels: Record<ReportType,string> = { course:'Course Report', enrollment:'Enrollment Report', hostel:'Hostel Report', 'exam-fee':'Exam Fee Report' };
const endpoints: Record<ReportType,string> = { course:'/reports/course', enrollment:'/reports/enrollment', hostel:'/reports/hostel', 'exam-fee':'/reports/exam-fee' };
const money=(v:unknown)=>`₹${Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:0,maximumFractionDigits:2})}`;
const fmtDate=(v:unknown)=>{if(!v)return '—';const s=String(v);if(/^\d{2}\/\d{2}\/\d{4}$/.test(s))return s;const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toLocaleDateString('en-IN',{day:'2-digit',month:'2-digit',year:'numeric'});};
const esc=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;

const CourseTable=({rows}:{rows:any[]})=><table className="report-table"><thead><tr>{['#','Student ID','Full Name','Mobile','Email','DOB','Gender','Address','Parent Name','Parent Mobile','Guardian','Course','Batch','Admission Date','Status'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.student_id}-${i}`}><td>{i+1}</td><td>{r.student_id}</td><td>{r.full_name}</td><td>{r.mobile}</td><td>{r.email||'—'}</td><td>{fmtDate(r.date_of_birth)}</td><td>{r.gender||'—'}</td><td>{r.address||'—'}</td><td>{r.parent_name||'—'}</td><td>{r.parent_mobile||'—'}</td><td>{r.guardian_type||'—'}</td><td>{r.course_name||'—'}</td><td>{r.batch_name||'—'}</td><td>{fmtDate(r.admission_date)}</td><td>{r.status}</td></tr>)}</tbody></table>;
const EnrollmentTable=({rows}:{rows:any[]})=><table className="report-table"><thead><tr>{['#','Student ID','Student Name','Mobile','Email','Master Course','Course','Batch','Enrollment Date','Status','Application Fee','Course Fee','Materials Fee','Total Fee','Discount','Paid','Balance'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.enrollment_id}><td>{i+1}</td><td>{r.student_code}</td><td>{r.full_name}</td><td>{r.mobile}</td><td>{r.email||'—'}</td><td>{r.master_course||'—'}</td><td>{r.course_name||'—'}</td><td>{r.batch_name||'—'}</td><td>{fmtDate(r.enrollment_date)}</td><td>{r.status}</td><td>{money(r.application_fee)}</td><td>{money(r.course_fee)}</td><td>{money(r.materials_fee)}</td><td>{money(r.total_fee)}</td><td>{money(r.discount)}</td><td>{money(r.amount_paid)}</td><td>{money(r.balance_due)}</td></tr>)}</tbody></table>;
const HostelTable=({rows}:{rows:any[]})=><table className="report-table"><thead><tr>{['#','Student ID','Student Name','Mobile','Email','Course','Batch','Admission Date','Hostel Fee','Mess Fee','Total Fee','Discount','Net Payable','Paid','Balance'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.hostel_record_id}><td>{i+1}</td><td>{r.student_code}</td><td>{r.full_name}</td><td>{r.mobile}</td><td>{r.email||'—'}</td><td>{r.course_name||'—'}</td><td>{r.batch_name||'—'}</td><td>{fmtDate(r.admission_date)}</td><td>{money(r.hostel_fee)}</td><td>{money(r.mess_fee)}</td><td>{money(r.total_fee)}</td><td>{money(r.discount)}</td><td>{money(r.net_payable)}</td><td>{money(r.amount_paid)}</td><td>{money(r.balance_due)}</td></tr>)}</tbody></table>;
const ExamTable=({rows}:{rows:any[]})=><table className="report-table"><thead><tr>{['#','Student ID','Student Name','Course','Batch','Exam Fee','Discount','Net Payable','Paid','Balance','Status'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.student_code}-${i}`}><td>{i+1}</td><td>{r.student_code}</td><td>{r.full_name}</td><td>{r.course_name||'—'}</td><td>{r.batch_name||'—'}</td><td>{money(r.exam_fee)}</td><td>{money(r.discount)}</td><td>{money(r.net_payable)}</td><td>{money(r.amount_paid)}</td><td>{money(r.balance_due)}</td><td>{r.payment_status}</td></tr>)}</tbody></table>;

const ReportsPage:React.FC=()=>{
 const [type,setType]=useState<ReportType>('course'); const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await api.get(endpoints[type]);setRows(r.data.data||[]);}catch(err:any){toast.error(err.response?.data?.message||`Failed to load ${labels[type]}`);setRows([]);}finally{setLoading(false);}};
 useEffect(()=>{load();},[type]);
 const totals=useMemo(()=>{const sum=(k:string)=>rows.reduce((a,r)=>a+Number(r[k]||0),0);if(type==='course')return [['RECORDS',rows.length],['ACTIVE',rows.filter(r=>r.status==='active').length]];if(type==='enrollment'||type==='hostel')return [['RECORDS',rows.length],['TOTAL FEE',money(sum('total_fee'))],['DISCOUNT',money(sum('discount'))],['PAID',money(sum('amount_paid'))],['BALANCE',money(sum('balance_due'))]];return [['RECORDS',rows.length],['EXAM FEE',money(sum('exam_fee'))],['DISCOUNT',money(sum('discount'))],['PAID',money(sum('amount_paid'))],['BALANCE',money(sum('balance_due'))]];},[rows,type]);
 const exportCsv=()=>{let header:string[]=[];let data:any[][]=[];if(type==='course'){header=['#','Student ID','Full Name','Mobile','Email','DOB','Gender','Address','Parent Name','Parent Mobile','Guardian','Course','Batch','Admission Date','Status'];data=rows.map((r,i)=>[i+1,r.student_id,r.full_name,r.mobile,r.email||'',fmtDate(r.date_of_birth),r.gender||'',r.address||'',r.parent_name||'',r.parent_mobile||'',r.guardian_type||'',r.course_name||'',r.batch_name||'',fmtDate(r.admission_date),r.status]);}else if(type==='enrollment'){header=['#','Student ID','Student Name','Mobile','Email','Master Course','Course','Batch','Enrollment Date','Status','Application Fee','Course Fee','Materials Fee','Total Fee','Discount','Paid','Balance'];data=rows.map((r,i)=>[i+1,r.student_code,r.full_name,r.mobile,r.email||'',r.master_course||'',r.course_name||'',r.batch_name||'',fmtDate(r.enrollment_date),r.status,Number(r.application_fee||0),Number(r.course_fee||0),Number(r.materials_fee||0),Number(r.total_fee||0),Number(r.discount||0),Number(r.amount_paid||0),Number(r.balance_due||0)]);}else if(type==='hostel'){header=['#','Student ID','Student Name','Mobile','Email','Course','Batch','Admission Date','Hostel Fee','Mess Fee','Total Fee','Discount','Net Payable','Paid','Balance'];data=rows.map((r,i)=>[i+1,r.student_code,r.full_name,r.mobile,r.email||'',r.course_name||'',r.batch_name||'',fmtDate(r.admission_date),Number(r.hostel_fee||0),Number(r.mess_fee||0),Number(r.total_fee||0),Number(r.discount||0),Number(r.net_payable||0),Number(r.amount_paid||0),Number(r.balance_due||0)]);}else{header=['#','Student ID','Student Name','Course','Batch','Exam Fee','Discount','Net Payable','Paid','Balance','Status'];data=rows.map((r,i)=>[i+1,r.student_code,r.full_name,r.course_name||'',r.batch_name||'',Number(r.exam_fee||0),Number(r.discount||0),Number(r.net_payable||0),Number(r.amount_paid||0),Number(r.balance_due||0),r.payment_status]);}const lines=[header,...data].map(row=>row.map(esc).join(','));const blob=new Blob(['\uFEFF'+lines.join('\r\n')],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${type}-report.csv`;a.click();URL.revokeObjectURL(url);};
 const table=type==='course'?<CourseTable rows={rows}/>:type==='enrollment'?<EnrollmentTable rows={rows}/>:type==='hostel'?<HostelTable rows={rows}/>:<ExamTable rows={rows}/>;
 return <div><div className="page-header"><div><h1 className="page-title">Reports</h1><p className="page-subtitle">Current database reports with consistent dates, spacing, fonts and numbers.</p></div><button className="btn btn-secondary" onClick={load}><FiRefreshCw/> Refresh</button></div><div className="card report-selector">{(['course','enrollment','hostel','exam-fee'] as ReportType[]).map(t=><button key={t} className={`report-type-btn ${type===t?'active':''}`} onClick={()=>setType(t)}><FiFileText/> {labels[t]}</button>)}</div><div className="card report-print-area"><div className="report-title-row"><div><h2>{labels[type]}</h2><p>Generated from current ERP data · {new Date().toLocaleDateString('en-IN')}</p></div><div className="report-actions"><button className="btn btn-secondary" onClick={exportCsv} disabled={!rows.length}><FiDownload/> Export CSV</button><button className="btn btn-secondary" onClick={()=>window.print()} disabled={!rows.length}><FiPrinter/> Print</button></div></div><div className="report-summary">{totals.map(([k,v])=><div className="report-summary-card" key={String(k)}><span>{k}</span><strong>{v}</strong></div>)}</div>{loading?<div className="empty-state">Loading report…</div>:rows.length===0?<div className="empty-state"><h3>No data</h3><p>No records are available for this report.</p></div>:<div className="report-table-wrap">{table}</div>}</div></div>;
};
export default ReportsPage;
